name: my_expense
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0


  get: ^4.6.6

  fl_chart: ^0.70.2


  intl: ^0.19.0
  path_provider: ^2.1.3

  cupertino_icons: ^1.0.6

  local_auth: ^2.2.0
  flutter_secure_storage: ^9.2.2


  share_plus: ^9.0.0
  file_picker: ^8.0.5
  csv: ^6.0.0
  pdf: ^3.11.1


  flutter_slidable: ^3.1.1
  shimmer: ^3.0.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Poppins-Bold.ttf
  #         weight: 700